AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Auth App API

  SAM Template for Auth App API

Parameters:
  CodeBucketName:
    Type: String
    Default: 'auth api'
    Description: (Required) The name of the S3 bucket where the Lambda function code is stored. Minimum 3 characters

  ExposeType:
    Type: String
    Default: 'FunctionUrl'
    AllowedValues: ['FunctionUrl', 'ApiGateway']
    Description: (Required) The type of exposure for the API. FunctionUrl or ApiGateway

Conditions:
  IsFunctionUrlAuth: !Equals [!Ref ExposeType, "FunctionUrl"]
  IsApiGatewayAuth: !Equals [!Ref ExposeType, "ApiGateway"]

Resources:
  AuthApi:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name: auth-api
      ProtocolType: HTTP
    Condition: IsApiGatewayAuth
    
  ProxyRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref AuthApi
      RouteKey: 'ANY /{proxy+}'
      AuthorizationType: NONE
      OperationName: ApiEndpoints
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref ProxyRouteAnyMethod
    Condition: IsApiGatewayAuth
    
  ProxyRouteAnyMethod:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref AuthApi
      PayloadFormatVersion: '2.0'
      Description: ProxyRoute Integration
      IntegrationType: AWS_PROXY
      IntegrationUri:
        Fn::Sub:
          arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${AuthApiLambdaFunction.Arn}/invocations
    Condition: IsApiGatewayAuth
      
  Deployment:
    Type: AWS::ApiGatewayV2::Deployment
    DependsOn:
      - ProxyRoute
    Properties:
      ApiId: !Ref AuthApi
    Condition: IsApiGatewayAuth
  Stage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      StageName: prod
      Description: Prod Stage
      DeploymentId: !Ref Deployment
      ApiId: !Ref AuthApi
    Condition: IsApiGatewayAuth
    
  AuthApiLambdaFunctionPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - AuthApi
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref AuthApiLambdaFunction
      Principal: apigateway.amazonaws.com
    Condition: IsApiGatewayAuth
    
  AuthApiTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "pk"
          AttributeType: "S"
        - AttributeName: "sk"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "pk"
          KeyType: "HASH"
        - AttributeName: "sk"
          KeyType: "RANGE"
      BillingMode:
        PAY_PER_REQUEST
      TimeToLiveSpecification:
        AttributeName: "ttl"
        Enabled: true
      SSESpecification:
        SSEEnabled: True
      TableName: auth

  AuthApiLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: AuthApiLambdaFunction
      CodeUri:
        Bucket: !Ref CodeBucketName
        Key: deploy.zip
      Handler: Api
      Role: !GetAtt AuthApiLambdaFunctionExecutionRole.Arn
      MemorySize: 512
      Timeout: 180
      Runtime: dotnet8
      Environment:
        Variables:
          TABLE_NAME: auth
      Policies:
        - DynamoDBCrudPolicy:
            TableName: auth
            
  AuthApiApiFunctionUrl:
    Type: AWS::Lambda::Url
    Properties:
      AuthType: NONE
      TargetFunctionArn: !Ref AuthApiLambdaFunction
    Condition: IsFunctionUrlAuth

  AuthApiFunctionUrlPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - AuthApiLambdaFunction
    Properties:
      Action: lambda:InvokeFunctionUrl
      FunctionName: !Ref AuthApiLambdaFunction
      FunctionUrlAuthType: 'NONE'
      Principal: "*"
      
  AuthApiLambdaFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/AuthApiLambdaFunction"
      RetentionInDays: 14
  
  AuthApiLambdaFunctionExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: allowLambdaLogs
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:*
                Resource: arn:aws:logs:*:*:*
        - PolicyName: AuthApiLambdaDbPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:*
                Resource: !GetAtt AuthApiTable.Arn
        
        - PolicyName: AuthApiLambdaSNSPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sns:*
                Resource: arn:aws:sns:*:*:*
                
        - PolicyName: AuthApiLambdaSQSPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sqs:*
                Resource: arn:aws:sqs:*:*:*
        - PolicyName: allowParameterStore
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ssm:GetParameter
                  - ssm:GetParametersByPath
                Resource: '*'
  
  AuthApiEventBus:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: AuthApiEventBus

  AuthApiEventBusParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /auth-api/EventBusSettings
      Type: String
      Value: !Join [ '', [ '{"IsEnabled":true,"TopicArn":"',!Ref AuthApiEventBus,'"}' ] ]
      Description: AuthApiEventBus
      
  JwtParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /auth-api/Jwt
      Type: String
      Value: 'please fill'
      Description: JWT
  
  PasswordSaltParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /auth-api/PasswordSalt
      Type: String
      Value: 'please fill'
      Description: JWT
  
  SmsProvidersParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /auth-api/SmsProviders
      Type: String
      Value: 'please fill'
      Description: JWT
  
  MediaApiApiKey:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /auth-api/ApiKeyValidationSettings
      Type: String
      Value: !Join [ '', [ '{"IsEnabled":false,"HeaderName":"x-api-key","WhiteList":["/swagger"],"ApiKey":"',!Ref AWS::StackId,'"}' ] ]
      Description: AuthApiKeyValidationSettings
  
  AllowedPhonesParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /auth-api/AllowedPhones
      Type: String
      Value: '{"AllowAll":false,"Phones":[""],"Code":"1111"}'
      Description: AuthApiKeyValidationSettings
      
  GoogleAuthOptionsParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /auth-api/GoogleAuthOptions
      Type: String
      Value: '{"IsEnabled":false,"ClientId":"please fill","ClientSecret":"please fill"}'
      Description: GoogleAuthOptions
      
  MicrosoftAuthOptionsParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /auth-api/MicrosoftAuthOptions
      Type: String
      Value: '{"IsEnabled":false,"ClientId":"please fill","ClientSecret":"please fill"}'
      Description: MicrosoftAuthOptions

  CaptchaParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /auth-api/CaptchaSettings
      Type: String
      Value: '{"Google": {"IsEnabled": true,"ValidationUrl": "https://www.google.com/recaptcha/api/siteverify","ServerKey": ""},"CloudFlare": {"IsEnabled": false, "ValidationUrl": "https://challenges.cloudflare.com/turnstile/v0/siteverify","SecretKey":""}}'
      Description: CaptchaValidationSettings
  
  AdminUserParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: /auth-api/AdminUserOptions
      Type: String
      Value: '{"UserIds":[""]}'
